genre_images = {
    "Action": ["C:/Users/andre/Desktop/img/action.jpg", "C:/Users/andre/Desktop/img/action2.webp"],
    "Comedy": ["C:/Users/andre/Desktop/img/comedy.jpg", "C:/Users/andre/Desktop/img/comedy2.jpg"],
    "Drama": ["C:/Users/andre/Desktop/img/drama.webp", "C:/Users/andre/Desktop/img/drama2.jpg"],
    "Horror": ["C:/Users/andre/Desktop/img/horror.jpg", "C:/Users/andre/Desktop/img/horror2.webp"],
    "Sci-Fi": ["C:/Users/andre/Desktop/img/scifi.jpg","C:/Users/andre/Desktop/img/scifi2.jpg"],
    "Travel": ["C:/Users/andre/Desktop/img/travel.jpg", "C:/Users/andre/Desktop/img/travel2.jpg"],
    "Sports": ["C:/Users/andre/Desktop/img/sport.jpg", "C:/Users/andre/Desktop/img/sport2.jpg"],
    "New": ["C:/Users/andre/Desktop/img/new.jpg", "C:/Users/andre/Desktop/img/new2.webp"],
    "Music": ["C:/Users/andre/Desktop/img/music.jpg", "C:/Users/andre/Desktop/img/music2.webp"],
    "Games": ["C:/Users/andre/Desktop/img/games.jpg", "C:/Users/andre/Desktop/img/games2.jpg"],
    "Foreign": ["C:/Users/andre/Desktop/img/foreign.jpg", "C:/Users/andre/Desktop/img/foreign2.jpg", "C:/Users/andre/Desktop/img/foreign3.jpg"],
    "Family": ["C:/Users/andre/Desktop/img/family.jpg", "C:/Users/andre/Desktop/img/family2.jpg"],
    "Children": ["C:/Users/andre/Desktop/img/children.jpg", "C:/Users/andre/Desktop/img/children2.jpg"],
    "Documentary": ["C:/Users/andre/Desktop/img/documentary.jpg", "C:/Users/andre/Desktop/img/documentary2.jpg"],
    "Classics": ["C:/Users/andre/Desktop/img/classic.jpg", "C:/Users/andre/Desktop/img/classic2.jpg"],
    "Animation": ["C:/Users/andre/Desktop/img/animation.jpg", "C:/Users/andre/Desktop/img/animation2.jpg"],
}